//created on: 2014-10-27
package com.github.ligangty.droolstest.transform

//list any import classes here.
import java.util.*;
import droolsbook.transform.service.LegacyBankService;
import droolsbook.bank.model.Address;
import droolsbook.bank.model.Address.Country;

global LegacyBankService legacyService;

rule "find All Customers"
	dialect "mvel"
	when
		$customerMap : Map( )
			from legacyService.findAllCustomers()
	then
		$customerMap["_type_"] = "Customer"
		insert( $customerMap )
end