package com.github.ligangty.droolstest.droolsflow.loan;

import com.github.ligangty.droolstest.droolsflow.model.*;
import com.github.ligangty.droolstest.bank.model.*;
import com.github.ligangty.droolstest.bank.service.*;

import org.kie.api.runtime.process.ProcessInstance;

global ValidationReport validationReport

rule amountNotValid
ruleflow-group "validateLoan"
	when
		Loan(amount == null || amount < 0)
	then
		insert(new DefaultMessage());
end

rule durationYearsNotValid
ruleflow-group "validateLoan"
	when
		Loan(durationYears == null || durationYears < 0)
	then
		insert(new DefaultMessage());
end


//processInstance : WorkflowProcessInstance( 
//  getVariable("customerLoanRating") >=1000 )
//or
//customerLoanRating >= 1000
